# Azure pipeline to run Storage Account Creation
# ARM template file : templates/arm-template-storage-account.json
# Parameters file :  parameters/parameters_storage.json 
# Parameter storagePrefix value can be overrided by Pipeline Variable $(storagePrefix); default value is viv

name: $(Build.DefinitionName)_$(Build.BuildId)

trigger:
- main

variables:
  - group: vivanov1-var-group

pool:
  name: vivanovpc # Replace with your actual self-hosted agent pool name

jobs:
- job: DeployResources
  displayName: 'Deploy Storage Accounts and VM'
  steps:

  # Step 1: Install Azure CLI (if not already installed on the self-hosted agent)
  - task: AzureCLI@2
    displayName: 'Install Azure CLI'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'pscore'  # Changed to pscore
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Check if Azure CLI is installed
        if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
          Write-Host "Azure CLI is not installed. Installing Azure CLI..."
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash
          sudo apt-get install -y azure-cli
        }
        else {
          Write-Host "Azure CLI is already installed. Skipping installation."
        }

  # Step 2: Check if the resource group exists, if not, create it
  - task: AzureCLI@2
    displayName: 'Create Resource Group using Azure CLI'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'pscore'  # Changed to pscore
      scriptLocation: 'inlineScript'
      inlineScript: |
        $RESOURCE_GROUP = "$(resourceGroup)"
        $LOCATION = "$(location)"
        
        # Check if the resource group exists
        $RG_EXISTS = az group show --name $RESOURCE_GROUP --query "name" --output tsv
        
        if (-not $RG_EXISTS) {
          Write-Host "Resource group does not exist. Creating resource group..."
          az group create --name $RESOURCE_GROUP --location $LOCATION
        }
        else {
          Write-Host "Resource group '$RESOURCE_GROUP' already exists. Skipping creation."
        }

  # Step 3: Deploy Storage Account A using Azure CLI
  - task: AzureCLI@2
    displayName: 'Create Storage Account  using Azure CLI'  
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'pscore'  # Changed to pscore
      scriptLocation: 'inlineScript'
      inlineScript: |
        $storagePrefix = "$(storagePrefix)"
        $resourceGroup = "$(resourceGroup)"
        Write-Host "Creating Storage Account $storagePrefix...   in ResourceGroup $resourceGroup "
        az deployment group create `
          --resource-group $(resourceGroup) `
          --template-file $(Build.SourcesDirectory)/templates/arm-template-storage-account.json `
          --parameters $(Build.SourcesDirectory)/parameters/parameters_storage.json `
          --parameters storagePrefix=$(storagePrefix)
          
